package com.choudao.imsdk.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.choudao.imsdk.db.bean.Message;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ChatId = new Property(1, long.class, "chatId", false, "CHAT_ID");
        public final static Property ChatType = new Property(2, Integer.class, "chatType", false, "CHAT_TYPE");
        public final static Property SendUserId = new Property(3, Long.class, "sendUserId", false, "SEND_USER_ID");
        public final static Property SendUserType = new Property(4, Integer.class, "sendUserType", false, "SEND_USER_TYPE");
        public final static Property Content = new Property(5, String.class, "content", false, "CONTENT");
        public final static Property ContentType = new Property(6, Integer.class, "contentType", false, "CONTENT_TYPE");
        public final static Property SessionType = new Property(7, int.class, "sessionType", false, "SESSION_TYPE");
        public final static Property SendStatus = new Property(8, Integer.class, "sendStatus", false, "SEND_STATUS");
        public final static Property MsgId = new Property(9, long.class, "msgId", false, "MSG_ID");
        public final static Property Timestamp = new Property(10, Long.class, "timestamp", false, "TIMESTAMP");
        public final static Property ShowType = new Property(11, Integer.class, "showType", false, "SHOW_TYPE");
        public final static Property ShowSessionType = new Property(12, Integer.class, "showSessionType", false, "SHOW_SESSION_TYPE");
        public final static Property SrcContent = new Property(13, String.class, "srcContent", false, "SRC_CONTENT");
    };


    public MessageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CHAT_ID\" INTEGER NOT NULL ," + // 1: chatId
                "\"CHAT_TYPE\" INTEGER," + // 2: chatType
                "\"SEND_USER_ID\" INTEGER," + // 3: sendUserId
                "\"SEND_USER_TYPE\" INTEGER," + // 4: sendUserType
                "\"CONTENT\" TEXT," + // 5: content
                "\"CONTENT_TYPE\" INTEGER," + // 6: contentType
                "\"SESSION_TYPE\" INTEGER NOT NULL ," + // 7: sessionType
                "\"SEND_STATUS\" INTEGER," + // 8: sendStatus
                "\"MSG_ID\" INTEGER NOT NULL ," + // 9: msgId
                "\"TIMESTAMP\" INTEGER," + // 10: timestamp
                "\"SHOW_TYPE\" INTEGER," + // 11: showType
                "\"SHOW_SESSION_TYPE\" INTEGER," + // 12: showSessionType
                "\"SRC_CONTENT\" TEXT);"); // 13: srcContent
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_MESSAGE_TIMESTAMP ON MESSAGE" +
                " (\"TIMESTAMP\");");
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_MESSAGE_CHAT_ID_MSG_ID_SESSION_TYPE ON MESSAGE" +
                " (\"CHAT_ID\",\"MSG_ID\",\"SESSION_TYPE\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getChatId());
 
        Integer chatType = entity.getChatType();
        if (chatType != null) {
            stmt.bindLong(3, chatType);
        }
 
        Long sendUserId = entity.getSendUserId();
        if (sendUserId != null) {
            stmt.bindLong(4, sendUserId);
        }
 
        Integer sendUserType = entity.getSendUserType();
        if (sendUserType != null) {
            stmt.bindLong(5, sendUserType);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(6, content);
        }
 
        Integer contentType = entity.getContentType();
        if (contentType != null) {
            stmt.bindLong(7, contentType);
        }
        stmt.bindLong(8, entity.getSessionType());
 
        Integer sendStatus = entity.getSendStatus();
        if (sendStatus != null) {
            stmt.bindLong(9, sendStatus);
        }
        stmt.bindLong(10, entity.getMsgId());
 
        Long timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindLong(11, timestamp);
        }
 
        Integer showType = entity.getShowType();
        if (showType != null) {
            stmt.bindLong(12, showType);
        }
 
        Integer showSessionType = entity.getShowSessionType();
        if (showSessionType != null) {
            stmt.bindLong(13, showSessionType);
        }
 
        String srcContent = entity.getSrcContent();
        if (srcContent != null) {
            stmt.bindString(14, srcContent);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Message readEntity(Cursor cursor, int offset) {
        Message entity = new Message( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // chatId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // chatType
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // sendUserId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // sendUserType
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // content
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // contentType
            cursor.getInt(offset + 7), // sessionType
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // sendStatus
            cursor.getLong(offset + 9), // msgId
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // timestamp
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // showType
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // showSessionType
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // srcContent
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Message entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChatId(cursor.getLong(offset + 1));
        entity.setChatType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setSendUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setSendUserType(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setContent(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setContentType(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setSessionType(cursor.getInt(offset + 7));
        entity.setSendStatus(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setMsgId(cursor.getLong(offset + 9));
        entity.setTimestamp(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setShowType(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setShowSessionType(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setSrcContent(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Message entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Message entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
