# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'OCJ_RN_APP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCJ
  pod 'AFNetworking' 
  pod 'MBProgressHUD'
  pod 'MGJRouter'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MLeaksFinder'
  pod 'FHHFPSIndicator'
  pod 'Masonry'
#  pod 'TPKeyboardAvoiding'
  pod 'ASIHTTPRequest'
  pod 'pop', '1.0.9' #@wubin
  pod 'UMengAnalytics-NO-IDFA'#无IDFA版SDK @wubin
#  pod 'WebViewJavascriptBridge', '~> 4.1.5' #wubin
end
