package com.community.imsdk.db.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GROUP_MEMBER".
 */
public class GroupMember implements java.io.Serializable {

    private Long id;
    private long groupId;
    private long userId;
    private String remark;
    private Long memberId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GroupMember() {
    }

    public GroupMember(Long id) {
        this.id = id;
    }

    public GroupMember(Long id, long groupId, long userId, String remark, Long memberId) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.remark = remark;
        this.memberId = memberId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    // KEEP METHODS - put your custom methods here
    public GroupMember(long groupId, long userId) {
        this.groupId = groupId;
        this.userId = userId;
    }
    // KEEP METHODS END

}
