package com.community.imsdk.db.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.text.TextUtils;
// KEEP INCLUDES END
/**
 * Entity mapped to table "GROUP_INFO".
 */
public class GroupInfo implements java.io.Serializable {

    private Long id;
    private long groupId;
    private String name;
    private String localName;
    private String notice;
    private String headImgUrl;
    private Integer type;
    private Long holder;
    private Integer memberCount;
    private Integer memberVersion;
    private Integer infoVersion;
    private boolean isKickOut;
    private boolean isNewNotice;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GroupInfo() {
    }

    public GroupInfo(Long id) {
        this.id = id;
    }

    public GroupInfo(Long id, long groupId, String name, String localName, String notice, String headImgUrl, Integer type, Long holder, Integer memberCount, Integer memberVersion, Integer infoVersion, boolean isKickOut, boolean isNewNotice) {
        this.id = id;
        this.groupId = groupId;
        this.name = name;
        this.localName = localName;
        this.notice = notice;
        this.headImgUrl = headImgUrl;
        this.type = type;
        this.holder = holder;
        this.memberCount = memberCount;
        this.memberVersion = memberVersion;
        this.infoVersion = infoVersion;
        this.isKickOut = isKickOut;
        this.isNewNotice = isNewNotice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocalName() {
        return localName;
    }

    public void setLocalName(String localName) {
        this.localName = localName;
    }

    public String getNotice() {
        return notice;
    }

    public void setNotice(String notice) {
        this.notice = notice;
    }

    public String getHeadImgUrl() {
        return headImgUrl;
    }

    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getHolder() {
        return holder;
    }

    public void setHolder(Long holder) {
        this.holder = holder;
    }

    public Integer getMemberCount() {
        return memberCount;
    }

    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    public Integer getMemberVersion() {
        return memberVersion;
    }

    public void setMemberVersion(Integer memberVersion) {
        this.memberVersion = memberVersion;
    }

    public Integer getInfoVersion() {
        return infoVersion;
    }

    public void setInfoVersion(Integer infoVersion) {
        this.infoVersion = infoVersion;
    }

    public boolean getIsKickOut() {
        return isKickOut;
    }

    public void setIsKickOut(boolean isKickOut) {
        this.isKickOut = isKickOut;
    }

    public boolean getIsNewNotice() {
        return isNewNotice;
    }

    public void setIsNewNotice(boolean isNewNotice) {
        this.isNewNotice = isNewNotice;
    }

    // KEEP METHODS - put your custom methods here
    public String showName() {
        return TextUtils.isEmpty(name) ? localName : name;
    }
    // KEEP METHODS END

}
