package com.community.imsdk.db.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.text.TextUtils;
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_INFO".
 */
public class UserInfo implements java.io.Serializable {

    private Long id;
    private long userId;
    private Integer userType;
    private String name;
    private String title;
    private String remark;
    private String namePinYin;
    private String remarkPinYin;
    private String headImgUrl;
    private String phone;
    private String desc;
    private String address;
    private String shareUrl;
    private Integer questionCount;
    private Integer answerCount;
    private Integer followersCount;
    private Integer followingCount;

    // ADD TO  new profile
    private int beehive;
    private String levelsList;
    private String gender;
    private int followPitches;
    private int launchedPitches;
    private String education;
    private String experience;
    // ADD TO  new profile

    // KEEP FIELDS - put your custom fields here
    private String state;

    public UserInfo(String state) {
        this.state = state;
    }
    // KEEP FIELDS END

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, long userId, Integer userType, String name, String title, String remark, String namePinYin, String remarkPinYin, String headImgUrl, String phone, String desc, String address, String shareUrl, Integer questionCount, Integer answerCount, Integer followersCount, Integer followingCount) {
        this.id = id;
        this.userId = userId;
        this.userType = userType;
        this.name = name;
        this.title = title;
        this.remark = remark;
        this.namePinYin = namePinYin;
        this.remarkPinYin = remarkPinYin;
        this.headImgUrl = headImgUrl;
        this.phone = phone;
        this.desc = desc;
        this.address = address;
        this.shareUrl = shareUrl;
        this.questionCount = questionCount;
        this.answerCount = answerCount;
        this.followersCount = followersCount;
        this.followingCount = followingCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Integer getUserType() {
        return userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getNamePinYin() {
        return namePinYin;
    }

    public void setNamePinYin(String namePinYin) {
        this.namePinYin = namePinYin;
    }

    public String getRemarkPinYin() {
        return remarkPinYin;
    }

    public void setRemarkPinYin(String remarkPinYin) {
        this.remarkPinYin = remarkPinYin;
    }

    public String getHeadImgUrl() {
        return headImgUrl;
    }

    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getShareUrl() {
        return shareUrl;
    }

    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    public Integer getQuestionCount() {
        return questionCount == null ? 0 : questionCount;
    }

    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    public Integer getAnswerCount() {
        return answerCount == null ? 0 : answerCount;
    }

    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }

    public Integer getFollowersCount() {
        return followersCount == null ? 0 : followersCount;
    }

    public void setFollowersCount(Integer followersCount) {
        this.followersCount = followersCount;
    }

    public Integer getFollowingCount() {
        return followingCount == null ? 0 : followingCount;
    }

    public void setFollowingCount(Integer followingCount) {
        this.followingCount = followingCount;
    }

    public int getBeehive() {
        return beehive;
    }

    public void setBeehive(int beehive) {
        this.beehive = beehive;
    }

    public String getLevelsList() {
        return levelsList;
    }

    public void setLevelsList(String levelsList) {
        this.levelsList = levelsList;
    }

    public int getFollowPitches() {
        return followPitches;
    }

    public void setFollowPitches(int followPitches) {
        this.followPitches = followPitches;
    }

    public int getLaunchedPitches() {
        return launchedPitches;
    }

    public void setLaunchedPitches(int launchedPitches) {
        this.launchedPitches = launchedPitches;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    // KEEP METHODS - put your custom methods here

    public String showName() {
        return TextUtils.isEmpty(getRemark()) ? getName() : getRemark();
    }

    public String showPinYin() {
        return TextUtils.isEmpty(getRemarkPinYin()) ? getNamePinYin() : getRemarkPinYin();
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
    // KEEP METHODS END

}
