package com.choudao.imsdk.db.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SESSION_CONFIG".
 */
public class SessionConfig implements java.io.Serializable {

    private Long id;
    private long targetId;
    private Integer targetType;
    private int sessionType;
    private Boolean isTop;
    private long topTime;
    private Boolean isMute;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SessionConfig() {
    }

    public SessionConfig(Long id) {
        this.id = id;
    }

    public SessionConfig(Long id, long targetId, Integer targetType, int sessionType, Boolean isTop, long topTime, Boolean isMute) {
        this.id = id;
        this.targetId = targetId;
        this.targetType = targetType;
        this.sessionType = sessionType;
        this.isTop = isTop;
        this.topTime = topTime;
        this.isMute = isMute;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTargetId() {
        return targetId;
    }

    public void setTargetId(long targetId) {
        this.targetId = targetId;
    }

    public Integer getTargetType() {
        return targetType;
    }

    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    public int getSessionType() {
        return sessionType;
    }

    public void setSessionType(int sessionType) {
        this.sessionType = sessionType;
    }

    public Boolean getIsTop() {
        return isTop;
    }

    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    public long getTopTime() {
        return topTime;
    }

    public void setTopTime(long topTime) {
        this.topTime = topTime;
    }

    public Boolean getIsMute() {
        return isMute;
    }

    public void setIsMute(Boolean isMute) {
        this.isMute = isMute;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
